# Generated by Django 4.0.5 on 2022-07-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioNavType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Type de moyen radio',
                'verbose_name_plural': 'Types de moyen radio',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RadioNavStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Identifiant')),
                ('long_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom complet')),
                ('frequency', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fréquence')),
                ('latitude', models.IntegerField(default=0, help_text='(-1 si S) * (degrés * 3600 + minutes * 60 + secondes)', verbose_name='Latitude')),
                ('longitude', models.IntegerField(default=0, help_text='(-1 si W) * (degrés * 3600 + minutes * 60 + secondes)', verbose_name='Longitude')),
                ('range', models.CharField(blank=True, max_length=250, null=True, verbose_name='Portée')),
                ('airac', models.DateField(verbose_name='Cycle AIRAC')),
                ('types', models.ManyToManyField(related_name='stations', to='radionav.radionavtype')),
            ],
            options={
                'verbose_name': 'Moyens radio',
                'verbose_name_plural': 'Moyens radio',
                'ordering': ['short_name'],
            },
        ),
    ]
