# Generated by Django 4.0.5 on 2022-06-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filecategory_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticfile',
            old_name='file',
            new_name='pdf',
        ),
    ]
