# Generated by Django 3.2.11 on 2022-03-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzbaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Début de validité')),
                ('end', models.DateTimeField(verbose_name='Fin de validité')),
                ('pdf', models.FileField(max_length=251, upload_to='', verbose_name='PDF')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
            ],
            options={
                'verbose_name': 'Carte AZBA',
                'verbose_name_plural': 'Cartes AZBA',
                'ordering': ['start', 'end'],
                'unique_together': {('start', 'end')},
            },
        ),
    ]
