# Generated by Django 3.2.11 on 2022-03-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airfields', '0001_initial'),
        ('civ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('opening_min', models.PositiveIntegerField(default=9, help_text='(heure locale)', verbose_name='Ouverture au plus tôt')),
                ('opening_max', models.PositiveIntegerField(default=9, help_text='(heure locale)', verbose_name='Ouverture au plus tard')),
                ('closing_min', models.PositiveIntegerField(default=19, help_text='(heure locale)', verbose_name='Fermeture au plus tôt')),
                ('closing_max', models.PositiveIntegerField(default=21, help_text='(heure locale)', verbose_name='Fermeture au plus tard')),
                ('reference', models.ForeignKey(blank=True, help_text='Aérodrome de référence pour le calcul de la nuit aéronautique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='airfields.airfield')),
            ],
            options={
                'verbose_name': 'Horaires CIV',
            },
        ),
    ]
