# Generated by Django 4.0.5 on 2022-08-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civ', '0002_civschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AzbaMap',
        ),
    ]
