# Generated by Django 4.1.2 on 2022-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civ', '0004_azbaarea_azbaknownschedule_azbaschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='azbaarea',
            name='boundaries',
            field=models.JSONField(blank=True, null=True, verbose_name='Limites'),
        ),
        migrations.AddField(
            model_name='azbaarea',
            name='ceiling',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Plafond'),
        ),
        migrations.AddField(
            model_name='azbaarea',
            name='floor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Plancher'),
        ),
    ]
