# Generated by Django 4.1.2 on 2022-11-04 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('civ', '0006_alter_azbaarea_options_azbaarea_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='azbaknownschedule',
            name='from_d',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
