# Generated by Django 3.2.11 on 2022-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='airac',
        ),
        migrations.AddField(
            model_name='sectorfrequency',
            name='airac',
            field=models.DateField(default='2022-02-24', verbose_name='Cycle AIRAC'),
            preserve_default=False,
        ),
    ]
