# Generated by Django 3.2.13 on 2022-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('acc', '0002_auto_20220305_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='files',
            field=models.ManyToManyField(related_name='sectors', to='files.StaticFile'),
        ),
    ]
