# Generated by Django 4.0.5 on 2022-06-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_filecategory_files'),
        ('acc', '0003_sector_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='main_antenna',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='secondary_antenna',
        ),
        migrations.AddField(
            model_name='sector',
            name='alternate_antennas',
            field=models.ManyToManyField(
                blank=True, default=None, related_name='alternate_sectors', to='acc.antenna', verbose_name='Antennes secours'),
        ),
        migrations.AddField(
            model_name='sector',
            name='main_antennas',
            field=models.ManyToManyField(blank=True, default=None, related_name='main_sectors',
                                         to='acc.antenna', verbose_name='Antennes principales'),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='latitude',
            field=models.IntegerField(
                default=0, help_text='(-1 si S) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='longitude',
            field=models.IntegerField(
                default=0, help_text='(-1 si W) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='files',
            field=models.ManyToManyField(
                blank=True, related_name='sectors', to='files.staticfile'),
        ),
        migrations.CreateModel(
            name='SectorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('airac', models.DateField(verbose_name='Cycle AIRAC')),
                ('ceiling', models.CharField(blank=True,
                 max_length=25, null=True, verbose_name='Plafond')),
                ('floor', models.CharField(max_length=25, verbose_name='Plancher')),
                ('sector', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='acc.sector')),
            ],
            options={
                'verbose_name': 'Morceaux de secteur',
                'verbose_name_plural': 'Morceau de secteur',
            },
        ),
        migrations.CreateModel(
            name='SectorBoundaryVertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(
                    default=0, help_text='(-1 si S) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Latitude')),
                ('longitude', models.IntegerField(
                    default=0, help_text='(-1 si W) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Longitude')),
                ('comment', models.CharField(
                    max_length=250, verbose_name='Observations')),
                ('sector_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='boundaries', to='acc.sectorpart')),
            ],
            options={
                'verbose_name': 'Vertex de limite secteur',
                'verbose_name_plural': 'Limite secteur',
            },
        ),
    ]
