# Generated by Django 4.0.5 on 2022-06-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_remove_sector_main_antenna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Nom'),
        ),
    ]
