# Generated by Django 4.0.5 on 2022-06-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_alter_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='acc.controlcenter'),
        ),
    ]
