# Generated by Django 4.0.5 on 2022-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_alter_antenna_latitude_alter_antenna_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectorboundaryvertex',
            options={'ordering': ['rank'], 'verbose_name': 'Vertex de limite secteur', 'verbose_name_plural': 'Limite secteur'},
        ),
        migrations.AddField(
            model_name='sectorboundaryvertex',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
