# Generated by Django 4.0.5 on 2022-10-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_alter_sectorboundaryvertex_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectorboundaryvertex',
            options={'ordering': ['sort_order'], 'verbose_name': 'Vertex de limite secteur', 'verbose_name_plural': 'Limite secteur'},
        ),
        migrations.RenameField(
            model_name='sectorboundaryvertex',
            old_name='rank',
            new_name='sort_order',
        ),
    ]
