# Generated by Django 4.1.2 on 2022-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0009_alter_sectorboundaryvertex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorpart',
            name='boundaries',
            field=models.JSONField(blank=True, null=True, verbose_name='Limites'),
        ),
        migrations.DeleteModel(
            name='SectorBoundaryVertex',
        ),
    ]
