# Generated by Django 4.0.5 on 2022-10-15 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='zip_file',
            field=models.FileField(blank=True, help_text="Importer un nouveau fichier ZIP contenant l'arborescence XYZ des tuiles", null=True, upload_to='import/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Fichier Zip'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='mbtiles_file',
            field=models.FileField(blank=True, help_text='Importer un nouveau fichier MBTiles pour générer de nouvelles tuiles', null=True, upload_to='import/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mbtiles'])], verbose_name='Fichier MBTiles'),
        ),
    ]
