# Generated by Django 4.0.5 on 2022-10-31 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_maplayer_zip_file_alter_maplayer_mbtiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='zip_file',
            field=models.FileField(blank=True, help_text="Importer un nouveau fichier ZIP contenant l'arborescence des tuiles (Z/X/Y.ext où Z est le niveau de zoom et ext vaut png ou pbf)", null=True, upload_to='import/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Fichier Zip'),
        ),
    ]
