# Generated by Django 4.1.2 on 2022-11-01 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0004_layerfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, verbose_name='Intitulé')),
                ('kml_file', models.FileField(upload_to='kml/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['kml'])], verbose_name='Fichier KML')),
            ],
            options={
                'verbose_name': 'Carte KML',
                'verbose_name_plural': 'Cartes KML',
                'ordering': ['label'],
            },
        ),
    ]
