# Generated by Django 4.1.2 on 2022-11-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0005_kmlmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLMapAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text="Fichier nécessaire à la carte parente : icône, etc. Utiliser l'URL absolue (ex : https://domaine.example/media/kml/mon-fichier.png) de ce fichier telle quelle dans votre KML.", upload_to='kml/', verbose_name='Fichier')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.kmlmap')),
            ],
        ),
    ]
