# Generated by Django 4.1.2 on 2022-11-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0006_kmlmapasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='style_file',
            field=models.FileField(blank=True, help_text='Si les tuiles sont vectorielles (PBF), importer ici les styles à utiliser. ', null=True, upload_to='tiles/', verbose_name='Fichier de styles'),
        ),
        migrations.AlterField(
            model_name='kmlmapasset',
            name='file',
            field=models.FileField(help_text="Fichier nécessaire à la carte parente : icône, etc. Utiliser l'URL (ex : /media/kml/mon-fichier.png) de ce fichier telle quelle dans votre KML.", upload_to='kml/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='zip_file',
            field=models.FileField(blank=True, help_text="Importer un nouveau fichier ZIP contenant l'arborescence des tuiles (Z/X/Y.ext où Z est le niveau de zoom et ext vaut png ou pbf). Cette arborescence doit être à la racine du ZIP.", null=True, upload_to='import/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Fichier Zip'),
        ),
    ]
