# Generated by Django 4.1.2 on 2022-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0007_maplayer_style_file_alter_kmlmapasset_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='style_file',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Données GeoJSON'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='style',
            field=models.JSONField(blank=True, help_text='Si les tuiles sont vectorielles (PBF), importer ici les styles au format JSON', null=True, verbose_name='Données de style'),
        ),
    ]
