# Generated by Django 4.1.2 on 2022-11-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0008_remove_maplayer_style_file_maplayer_geojson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='geojson',
        ),
    ]
