# Generated by Django 3.2.11 on 2022-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AzbaMap',
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='map',
            name='airfield',
        ),
        migrations.DeleteModel(
            name='Airfield',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
