# Generated by Django 3.2.11 on 2022-03-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airfields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirfieldFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=7, verbose_name='Fréquence')),
                ('frequency_type', models.CharField(choices=[('APP', 'Approche'), ('TWR', 'Tour'), ('GND', 'Sol'), ('ATIS', 'ATIS'), ('AFIS', 'AFIS'), ('A/A', 'A/A')], max_length=4, verbose_name='Type de fréquence')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='airfields.airfield')),
            ],
            options={
                'verbose_name': 'Fréquence',
                'verbose_name_plural': 'Fréquences',
                'ordering': ['airfield'],
            },
        ),
    ]
