# Generated by Django 3.2.11 on 2022-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfields', '0002_airfieldfrequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airfieldfrequency',
            options={'ordering': ['-airac', 'airfield__icao_code', 'frequency_type'], 'verbose_name': 'Fréquence', 'verbose_name_plural': 'Fréquences'},
        ),
        migrations.AddField(
            model_name='airfieldfrequency',
            name='airac',
            field=models.DateField(default='2022-02-24', verbose_name='Cycle AIRAC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airfieldfrequency',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observations'),
        ),
    ]
