# Generated by Django 3.2.13 on 2022-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('airfields', '0003_auto_20220303_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield',
            name='files',
            field=models.ManyToManyField(related_name='airfields', to='files.StaticFile'),
        ),
    ]
