# Generated by Django 3.2.13 on 2022-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfields', '0004_airfield_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfield',
            name='latitude',
            field=models.IntegerField(default=0, help_text='(-1 si S) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='airfield',
            name='longitude',
            field=models.IntegerField(default=0, help_text='(-1 si W) * (degrés + minutes * 60 + secondes * 3600)', verbose_name='Longitude'),
        ),
    ]
