# Generated by Django 4.0.5 on 2022-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfields', '0006_alter_airfield_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airfield',
            name='latitude',
            field=models.IntegerField(default=0, help_text='(-1 si S) * (degrés * 3600 + minutes * 60 + secondes)', verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='airfield',
            name='longitude',
            field=models.IntegerField(default=0, help_text='(-1 si W) * (degrés * 3600 + minutes * 60 + secondes)', verbose_name='Longitude'),
        ),
    ]
